In [1]:
import pandas as pd

In [3]:
import os 
print(os.getcwd())

/Users/shashanks/fake-news-detector/models

In [8]:
fake_df = pd.read_csv('/Users/shashanks/fake-news-detector/data/Fake.csv')
true_df = pd.read_csv('/Users/shashanks/fake-news-detector/data/True.csv')

In [9]:
fake_df["label"] = 0
true_df["label"] = 1

In [10]:
df = pd.concat([fake_df, true_df], ignore_index=True)

In [18]:
df.head(100)

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
...,...,...,...,...,...
95,Roy Moore Supporting Republican LOSES It Afte...,If the scandal around the stories of Alabama S...,News,"November 14, 2017",0
96,That Story Trump Just Told The Press About Ob...,"On Tuesday, Donald Trump told a story about Ai...",News,"November 14, 2017",0
97,This 4-Year Old Tweet From Donald Trump Shows...,After Hollywood producer Harvey Weinstein was ...,News,"November 13, 2017",0
98,OOPS: Trump Judicial Nominee Didn’t Tell Cong...,This is a major conflict of interest that shou...,News,"November 13, 2017",0
99,Trump Laughs After Philippine Leader Calls Jo...,Donald Trump probably wishes the United States...,News,"November 13, 2017",0

In [17]:
df.shape

(44898, 5)

In [21]:
df.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [25]:
df['subject'].unique()

array(['News', 'politics', 'Government News', 'left-news', 'US_News',
       'Middle-east', 'politicsNews', 'worldnews'], dtype=object)

In [27]:
df.drop(columns=["subject", "date",] , inplace = True)

In [29]:
df["full_text"] = df["title"] + " " + df["text"]

In [34]:
df

,title,text,label,full_text
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,0,Donald Trump Sends Out Embarrassing New Year’...
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,0,Drunk Bragging Trump Staffer Started Russian ...
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",0,Sheriff David Clarke Becomes An Internet Joke...
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",0,Trump Is So Obsessed He Even Has Obama’s Name...
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,0,Pope Francis Just Called Out Donald Trump Dur...
...,...,...,...,...
44893,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,1,'Fully committed' NATO backs new U.S. approach...
44894,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",1,LexisNexis withdrew two products from Chinese ...
44895,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,1,Minsk cultural hub becomes haven from authorit...
44896,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,1,Vatican upbeat on possibility of Pope Francis ...
44897,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,1,Indonesia to buy $1.14 billion worth of Russia...

In [35]:
df[["full_text", "label"]].head()

                                           full_text  label
0   Donald Trump Sends Out Embarrassing New Year’...      0
1   Drunk Bragging Trump Staffer Started Russian ...      0
2   Sheriff David Clarke Becomes An Internet Joke...      0
3   Trump Is So Obsessed He Even Has Obama’s Name...      0
4   Pope Francis Just Called Out Donald Trump Dur...      0

In [37]:
df.drop(columns=["title", "text"], inplace=True)

In [38]:
df.head()
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   label      44898 non-null  int64
 1   full_text  44898 non-null  object
dtypes: int64(1), object(1)
memory usage: 701.7+ KB

In [47]:
import re 
import nltk
from nltk.corpus import stopwords 
from nltk.stem import WordNetLemmatizer

In [40]:
pip install nltk

Collecting nltk
  Using cached nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from nltk) (8.3.0)
Requirement already satisfied: joblib in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from nltk) (1.5.1)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.4.4-cp313-cp313-macosx_11_0_arm64.whl.metadata (40 kB)
Requirement already satisfied: tqdm in /Users/shashanks/Library/Python/3.13/lib/python/site-packages (from nltk) (4.67.1)
Using cached nltk-3.9.4-py3-none-any.whl (1.6 MB)
Downloading regex-2026.4.4-cp313-cp313-macosx_11_0_arm64.whl (289 kB)
Installing collected packages: regex, nltk
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [nltk]━━━━━━ 1/2 [nltk]
Successfully installed nltk-3.9.4 regex-2026.4.4

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [44]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/shashanks/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/shashanks/nltk_data...

True

In [50]:
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('English'))

In [51]:
def clean_text(text):
    text = text.lower()  
    text = re.sub(r'[^a-z]', ' ', text)  
    words = text.split()  
    words = [w for w in words if w not in stop_words]  
    words = [lemmatizer.lemmatize(w) for w in words] 
    return " ".join(words)

In [55]:
df["clean_text"] = df["full_text"].apply(clean_text)

In [56]:
df[["full_text", "clean_text"]].head()

,full_text,clean_text
0,Donald Trump Sends Out Embarrassing New Year’...,donald trump sends embarrassing new year eve m...
1,Drunk Bragging Trump Staffer Started Russian ...,drunk bragging trump staffer started russian c...
2,Sheriff David Clarke Becomes An Internet Joke...,sheriff david clarke becomes internet joke thr...
3,Trump Is So Obsessed He Even Has Obama’s Name...,trump obsessed even obama name coded website i...
4,Pope Francis Just Called Out Donald Trump Dur...,pope francis called donald trump christmas spe...

In [58]:
from sklearn.model_selection import train_test_split

X = df["clean_text"]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [61]:
print(X_train.shape)
print(X_test.shape)

(35918,)
(8980,)

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [72]:
vectorizer  = TfidfVectorizer(max_features = 5000)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [73]:
X_train_tfidf.shape
X_test_tfidf.shape

(8980, 5000)

In [74]:
# from sklearn.linear_model import LogisticRegression

# lr_model = LogisticRegression()

# lr_model.fit(X_train_tfidf, y_train)

LogisticRegression()

In [75]:
# y_pred = lr_model.predict(X_test_tfidf)

In [76]:
# from sklearn.metrics import accuracy_score, classification_report

# accuracy = accuracy_score(y_test, y_pred)

# print("Accuracy:", accuracy)

# print(classification_report(y_test, y_pred))

Accuracy: 0.9880846325167038
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4733
           1       0.99      0.99      0.99      4247

    accuracy                           0.99      8980
   macro avg       0.99      0.99      0.99      8980
weighted avg       0.99      0.99      0.99      8980

In [83]:
# from sklearn.naive_bayes import MultinomialNB

# nb_model = MultinomialNB()

# nb_model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [84]:
# nb_pred = nb_model.predict(X_test_tfidf)

In [79]:
# from sklearn.metrics import accuracy_score, classification_report

# accuracy = accuracy_score(y_test, nb_pred)

# print("Accuracy:", accuracy)

# print(classification_report(y_test, nb_pred))

Accuracy: 0.9306236080178174
              precision    recall  f1-score   support

           0       0.93      0.94      0.93      4733
           1       0.93      0.92      0.93      4247

    accuracy                           0.93      8980
   macro avg       0.93      0.93      0.93      8980
weighted avg       0.93      0.93      0.93      8980

In [85]:
# from sklearn.linear_model import PassiveAggressiveClassifier

# pac_model = PassiveAggressiveClassifier(max_iter=1000)

# pac_model.fit(X_train_tfidf, y_train)

PassiveAggressiveClassifier()

In [86]:

pac_pred = pac_model.predict(X_test_tfidf)

In [87]:
print("Accuracy:", accuracy_score(y_test, pac_pred))

print(classification_report(y_test, pac_pred))

Accuracy: 0.9943207126948775
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4733
           1       0.99      0.99      0.99      4247

    accuracy                           0.99      8980
   macro avg       0.99      0.99      0.99      8980
weighted avg       0.99      0.99      0.99      8980

In [88]:
import joblib

joblib.dump(pac_model, "fake_news_model.pkl")

joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

['tfidf_vectorizer.pkl']